
from dataclasses import dataclass


@dataclass(frozen=True)
class SourceData:
    name: str
    hash_id: str
    size: int


@dataclass(frozen=True)
class PatchData:
    name: str
    hash_id: str
    size: int
    source: str
    version: str
    version_id: tuple[int, int, int]


@dataclass(frozen=True)
class ModVersionData:
    name: str
    name_id: tuple[int, int, int]  # Name in tuple format
    builds: list[str]  # Supported builds for this release


try:
    # data.py is generated by prepare_patches.py during the build pipeline.
    from .data import builds, mod_versions, patch_map, patches  # type: ignore
except ModuleNotFoundError:
    builds: dict[str, SourceData] = {}
    patches: dict[str, PatchData] = {}
    mod_versions: dict[str, ModVersionData] = {}
    patch_map: dict[tuple[tuple[int, int, int], str], PatchData] = {}

__all__ = ["ModVersionData", "PatchData", "SourceData", "builds", "mod_versions", "patch_map", "patches"]
